<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.kPhTiwY' shared service.

return $this->privates['.service_locator.kPhTiwY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'packages' => ['privates', 'assets.packages', 'getAssets_PackagesService', false],
    'room' => ['privates', '.errored..service_locator.kPhTiwY.App\\Entity\\Room', NULL, 'Cannot autowire service ".service_locator.kPhTiwY": it references class "App\\Entity\\Room" but no such service exists.'],
], [
    'packages' => '?',
    'room' => 'App\\Entity\\Room',
]);
