<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.FowCItu' shared service.

return $this->privates['.service_locator.FowCItu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\FrontController::index' => ['privates', '.service_locator.PLDWHeZ', 'get_ServiceLocator_PLDWHeZService.php', true],
    'App\\Controller\\RoomController::delete' => ['privates', '.service_locator.3KUCuEw', 'get_ServiceLocator_3KUCuEwService.php', true],
    'App\\Controller\\RoomController::edit' => ['privates', '.service_locator.kPhTiwY', 'get_ServiceLocator_KPhTiwYService.php', true],
    'App\\Controller\\RoomController::index' => ['privates', '.service_locator.oJp9hgg', 'get_ServiceLocator_OJp9hggService.php', true],
    'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.g.xob4v', 'get_ServiceLocator_G_Xob4vService.php', true],
    'App\\Controller\\UnavailabilityController::delete' => ['privates', '.service_locator.KDCCGKS', 'get_ServiceLocator_KDCCGKSService.php', true],
    'App\\Controller\\UnavailabilityController::edit' => ['privates', '.service_locator.dt6R8Lr', 'get_ServiceLocator_Dt6R8LrService.php', true],
    'App\\Controller\\UnavailabilityController::new' => ['privates', '.service_locator.v9OVCEf', 'get_ServiceLocator_V9OVCEfService.php', true],
    'App\\Controller\\UnavailabilityController::sendEmail' => ['privates', '.service_locator.8ZuNAXa', 'get_ServiceLocator_8ZuNAXaService.php', true],
    'App\\Controller\\UserController::delete' => ['privates', '.service_locator.VrNUW8O', 'get_ServiceLocator_VrNUW8OService.php', true],
    'App\\Controller\\UserController::new' => ['privates', '.service_locator.8ZuNAXa', 'get_ServiceLocator_8ZuNAXaService.php', true],
    'App\\Controller\\FrontController:index' => ['privates', '.service_locator.PLDWHeZ', 'get_ServiceLocator_PLDWHeZService.php', true],
    'App\\Controller\\RoomController:delete' => ['privates', '.service_locator.3KUCuEw', 'get_ServiceLocator_3KUCuEwService.php', true],
    'App\\Controller\\RoomController:edit' => ['privates', '.service_locator.kPhTiwY', 'get_ServiceLocator_KPhTiwYService.php', true],
    'App\\Controller\\RoomController:index' => ['privates', '.service_locator.oJp9hgg', 'get_ServiceLocator_OJp9hggService.php', true],
    'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.g.xob4v', 'get_ServiceLocator_G_Xob4vService.php', true],
    'App\\Controller\\UnavailabilityController:delete' => ['privates', '.service_locator.KDCCGKS', 'get_ServiceLocator_KDCCGKSService.php', true],
    'App\\Controller\\UnavailabilityController:edit' => ['privates', '.service_locator.dt6R8Lr', 'get_ServiceLocator_Dt6R8LrService.php', true],
    'App\\Controller\\UnavailabilityController:new' => ['privates', '.service_locator.v9OVCEf', 'get_ServiceLocator_V9OVCEfService.php', true],
    'App\\Controller\\UnavailabilityController:sendEmail' => ['privates', '.service_locator.8ZuNAXa', 'get_ServiceLocator_8ZuNAXaService.php', true],
    'App\\Controller\\UserController:delete' => ['privates', '.service_locator.VrNUW8O', 'get_ServiceLocator_VrNUW8OService.php', true],
    'App\\Controller\\UserController:new' => ['privates', '.service_locator.8ZuNAXa', 'get_ServiceLocator_8ZuNAXaService.php', true],
], [
    'App\\Controller\\FrontController::index' => '?',
    'App\\Controller\\RoomController::delete' => '?',
    'App\\Controller\\RoomController::edit' => '?',
    'App\\Controller\\RoomController::index' => '?',
    'App\\Controller\\SecurityController::login' => '?',
    'App\\Controller\\UnavailabilityController::delete' => '?',
    'App\\Controller\\UnavailabilityController::edit' => '?',
    'App\\Controller\\UnavailabilityController::new' => '?',
    'App\\Controller\\UnavailabilityController::sendEmail' => '?',
    'App\\Controller\\UserController::delete' => '?',
    'App\\Controller\\UserController::new' => '?',
    'App\\Controller\\FrontController:index' => '?',
    'App\\Controller\\RoomController:delete' => '?',
    'App\\Controller\\RoomController:edit' => '?',
    'App\\Controller\\RoomController:index' => '?',
    'App\\Controller\\SecurityController:login' => '?',
    'App\\Controller\\UnavailabilityController:delete' => '?',
    'App\\Controller\\UnavailabilityController:edit' => '?',
    'App\\Controller\\UnavailabilityController:new' => '?',
    'App\\Controller\\UnavailabilityController:sendEmail' => '?',
    'App\\Controller\\UserController:delete' => '?',
    'App\\Controller\\UserController:new' => '?',
]);
