<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.KDCCGKS' shared service.

return $this->privates['.service_locator.KDCCGKS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'emailManager' => ['privates', 'App\\Service\\EmailManager', 'getEmailManagerService.php', true],
    'mailer' => ['services', 'swiftmailer.mailer.default', 'getSwiftmailer_Mailer_DefaultService.php', true],
    'unavailability' => ['privates', '.errored..service_locator.KDCCGKS.App\\Entity\\Unavailability', NULL, 'Cannot autowire service ".service_locator.KDCCGKS": it references class "App\\Entity\\Unavailability" but no such service exists.'],
    'unavailabilityManager' => ['privates', 'App\\Service\\UnavailabilityManager', 'getUnavailabilityManagerService.php', true],
], [
    'emailManager' => 'App\\Service\\EmailManager',
    'mailer' => '?',
    'unavailability' => 'App\\Entity\\Unavailability',
    'unavailabilityManager' => 'App\\Service\\UnavailabilityManager',
]);
