<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Service\EmailManager' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/Service/EmailManager.php';

return $this->privates['App\\Service\\EmailManager'] = new \App\Service\EmailManager(($this->services['templating'] ?? $this->load('getTemplatingService.php')));
