<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'fullcalendar.service.calendar' shared service.

include_once \dirname(__DIR__, 4).'/vendor/toiba/fullcalendar-bundle/Service/Calendar.php';
include_once \dirname(__DIR__, 4).'/vendor/toiba/fullcalendar-bundle/Service/SerializerInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/toiba/fullcalendar-bundle/Service/Serializer.php';

return $this->services['fullcalendar.service.calendar'] = new \Toiba\FullCalendarBundle\Service\Calendar(new \Toiba\FullCalendarBundle\Service\Serializer(), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()));
