<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.PLDWHeZ' shared service.

return $this->privates['.service_locator.PLDWHeZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'roomRepository' => ['privates', 'App\\Repository\\RoomRepository', 'getRoomRepositoryService.php', true],
    'unavailabilityRepository' => ['privates', 'App\\Repository\\UnavailabilityRepository', 'getUnavailabilityRepositoryService.php', true],
    'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService.php', true],
], [
    'roomRepository' => 'App\\Repository\\RoomRepository',
    'unavailabilityRepository' => 'App\\Repository\\UnavailabilityRepository',
    'userRepository' => 'App\\Repository\\UserRepository',
]);
