<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.oJp9hgg' shared service.

return $this->privates['.service_locator.oJp9hgg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'featuresProvider' => ['services', 'App\\Provider\\FeaturesProvider', 'getFeaturesProviderService.php', true],
    'roomRepository' => ['privates', 'App\\Repository\\RoomRepository', 'getRoomRepositoryService.php', true],
], [
    'featuresProvider' => 'App\\Provider\\FeaturesProvider',
    'roomRepository' => 'App\\Repository\\RoomRepository',
]);
