<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.VrNUW8O' shared service.

return $this->privates['.service_locator.VrNUW8O'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'emailManager' => ['privates', 'App\\Service\\EmailManager', 'getEmailManagerService.php', true],
    'mailer' => ['services', 'swiftmailer.mailer.default', 'getSwiftmailer_Mailer_DefaultService.php', true],
    'unavailabilityManager' => ['privates', 'App\\Service\\UnavailabilityManager', 'getUnavailabilityManagerService.php', true],
    'unavailabilityRepository' => ['privates', 'App\\Repository\\UnavailabilityRepository', 'getUnavailabilityRepositoryService.php', true],
    'userManager' => ['privates', 'App\\Service\\UserManager', 'getUserManagerService.php', true],
], [
    'emailManager' => 'App\\Service\\EmailManager',
    'mailer' => '?',
    'unavailabilityManager' => 'App\\Service\\UnavailabilityManager',
    'unavailabilityRepository' => 'App\\Repository\\UnavailabilityRepository',
    'userManager' => 'App\\Service\\UserManager',
]);
