<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMx3YNul\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMx3YNul/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMx3YNul.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMx3YNul\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerMx3YNul\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Mx3YNul',
    'container.build_id' => '6baf6657',
    'container.build_time' => 1652268720,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMx3YNul');
