<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container21FLbO3\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container21FLbO3/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container21FLbO3.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container21FLbO3\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container21FLbO3\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '21FLbO3',
    'container.build_id' => 'a6095d4c',
    'container.build_time' => 1649939108,
], __DIR__.\DIRECTORY_SEPARATOR.'Container21FLbO3');
